#!/bin/bash

# By Grant Perkins, 2019

# Make directories used in training
mkdir /tensorflow/models/research/learn
mkdir /tensorflow/models/research/learn/ckpt

# Remove directories created during training
rm -rf /tensorflow/models/research/learn/train
rm -rf /tensorflow/models/research/learn/models

cd /tensorflow/models/research

# Download checkpoints for MobileNet v2 hosted by Google
cp model_main.py ./object_detection/model_main.py
cp model_lib.py ./object_detection/model_lib.py

printf ".\nDownloading model"
./prepare_checkpoint_and_dataset.sh --network_type mobilenet_v2_ssd --train_whole_model false  > /dev/null 2> /dev/null
./tar_to_record.sh

cd /opt/ml/input/data/training
classes=$(python3 /tensorflow/models/research/labels.py)
cd /tensorflow/models/research

sed -i "s%NUM_CLASSES%${classes}%g" "./pipeline.config"

# Get number of epochs from SageMaker
TRAIN_STEPS=$(python3 hyper.py)

BATCH_SIZE=$(python3 batch.py)

sed -i "s%BATCH_SIZE_PARAM%${BATCH_SIZE}%g" "./pipeline.config"

printf ".\nHyperparameters parsed"

# Copy custom pipeline into docker
cp pipeline.config /tensorflow/models/research/learn/ckpt/pipeline.config

printf ".\nBeginning training on Docker image"
./retrain_detection_model.sh --num_training_steps $TRAIN_STEPS --num_eval_steps 100 > output.txt 2> output.txt

python3 accuracy.py > accuracy.txt
cat accuracy.txt
cp accuracy.txt /opt/ml/model/accuracy.txt

printf ".\nConverting checkpoint to tflite"
./convert_checkpoint_to_edgetpu_tflite.sh --checkpoint_num $TRAIN_STEPS > /dev/null 2>&1
cp ./learn/models/output_tflite_graph.tflite /opt/ml/model/unoptimized.tflite


printf ".\nCompiling model for Edge TPU"
edgetpu_compiler ./learn/models/output_tflite_graph.tflite -o /opt/ml/model/ > /dev/null 2>&1

cp /opt/ml/input/data/training/map.pbtxt /opt/ml/model/map.pbtxt

rm /opt/ml/model/output_tflite_graph_edgetpu.log

mv /opt/ml/model/output_tflite_graph_edgetpu.tflite /opt/ml/model/model.tflite